stages:
- name: Crear Imagen
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: andreeavalos/pipeline-database
      pushRemote: true
      registry: 01
- name: Crear en k8s
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
